#!/bin/sh

PID_FILE=/var/run/amos.pid
RUN=/usr/local/bin/player
ARGS="-d6 -p7000 /home/amos/amos/configs/amos/amos.cfg"

start_amos_server() {
	start-stop-daemon --pidfile $PID_FILE --make-pidfile --background --quiet --chuid amos --group amos --chdir /home/amos --exec $RUN --start -- $ARGS
}

stop_amos_server() {
	start-stop-daemon --pidfile $PID_FILE --quiet --retry 2 --stop
}


case "$1" in
	start)
		echo 'AMOS ready' | festival --tts
		start_amos_server
	;;
	stop)
		echo "AMOS shutting down" | festival --tts
		stop_amos_server
	;;
	restart)
		stop_amos_server
		start_amos_server
	;;
	*)
		echo "$0 <start|stop|restart>"
	;;
esac

exit 0
